export const LOGIN = "auth/LOGIN";
export const LOGIN_FAILED = "auth/LOGIN_FAILED";
export const LOGIN_COMPLETED = "auth/LOGIN_COMPLETED";

export const AUTHENTICATED = "auth/AUTHENTICATED";
export const AUTHORIZATION_FAILED = "auth/AUTHORIZATION_FAILED";

export const LOGOUT = "auth/LOGOUT";
export const DESTROY = "auth/DESTROY_SESSION";
export const INITIALIZE = "auth/INITIALIZE_SESSION";
export const SET_REDIRECT_AFTER_LOGIN = "auth/SET_REDIRECT_AFTER_LOGIN";

export const SIGNUP = "auth/SIGNUP";

export const FORGOT_PASSWORD = "auth/FORGOT_PASSWORD";

export const UPDATE_PROFILE_PIC = "auth/UPDATE_PROFILE_PIC";
export const UPDATE_PROFILE_PIC_COMPLETED = "auth/UPDATE_PROFILE_PIC_COMPLETED";

export const CHANGE_PASSWORD = "auth/CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAILED = "auth/CHANGE_PASSWORD_FAILED";
export const CHANGE_PASSWORD_COMPLETED = "auth/CHANGE_PASSWORD_COMPLETED";

export const UPDATE_PROFILE = "auth/UPDATE_PROFILE";
export const UPDATE_PROFILE_FAILED = "auth/UPDATE_PROFILE_FAILED";
export const UPDATE_PROFILE_COMPLETED = "auth/UPDATE_PROFILE_COMPLETED";

