export const ErrorMessage = {
  OTP_Invalid: "Invalid OTP",
  EMPTY_EMAIL: "Email Id is required",
  EMPTY_USER: "User name is required",
  EMPTY_EVENT: "Event name is required",
  EMPTY_EVENT_INFO: "Event info is required",
  EMPTY_EVENT_LOCATION: "Event location is required",
  EMPTY_EVENT_START_DATE: "Event start date is required",
  EMPTY_EVENT_END_DATE: "Event end date is required",
  EMPTY_OTP: "OTP is requied",
  EMPTY_PASS: "Password is requied",
  WRONG_PASS:
    'Incorrect Password. Please try again or click on "Forgot Password" below.',
  PASSWORD_LENGTH: "Password must be minimum of 8 characters",
  LOWER_UPPER: "1 Lower and Upper case",
  SPECIAL_CHARACTER: "1 Special Character",
  MIN_NUMBER: "1 Number",
  EMAIL_VALID: "Are you sure you entered the valid Email Id?",
  REQUIRED: "Required",
  CONFIRM_PASS: "Both passwords must match",
  NAME_VALID:
    'This field can only contain "Alphanumeric" values. Please try again.',
  FIRST_EMPTY: "First Name is requied",
  LAST_EMPTY: "Last Name is requied",
  PHONE_EMPTY: "Phone Number is requied",
  PHONE_LENGTH: "Phone Number must be between 10-13 digits.",
};
