export const ErrorMessage = {
  OTP_Invalid: "Invalid OTP",
  EMPTY_EMAIL: "Email Id can't be empy",
  EMPTY_USER: "User name can't be empy",
  EMPTY_EVENT: "Event name can't be empy",
  EMPTY_EVENT_INFO: "Event info can't be empy",
  EMPTY_EVENT_LOCATION: "Event location can't be empy",
  EMPTY_OTP: "OTP can't be empty",
  EMPTY_PASS: "Password can't be empty",
  WRONG_PASS:
    'Incorrect Password. Please try again or click on "Forgot Password" below.',
  PASSWORD_LENGTH: "Password must be minimum of 8 characters",
  LOWER_UPPER: "1 Lower and Upper case",
  SPECIAL_CHARACTER: "1 Special Character",
  MIN_NUMBER: "1 Number",
  EMAIL_VALID: "Are you sure you entered the valid Email Id?",
  REQUIRED: "Required",
  CONFIRM_PASS: "Both passwords must match",
  NAME_VALID:
    'This field can only contain "Alphanumeric" values. Please try again.',
  FIRST_EMPTY: "First Name can't be empty",
  LAST_EMPTY: "Last Name can't be empty",
  PHONE_EMPTY: "Phone Number can't be empty",
  PHONE_LENGTH: "Phone Number must be between 10-13 digits.",
};
